USE SINGLE_STAGE
GO

DELETE FROM EMPLOYEES
INSERT INTO EMPLOYEES
	(username, Password)
	VALUES
	('admin','$2a$11$SXBkSrxs/61.hQLU8xsbce1FAFCSIxAhn7QLh.kfvfbyJdhiRfZx2')

SELECT * FROM EMPLOYEES ORDER BY id

