USE SINGLE_STAGE
GO


ALTER TABLE PERFORMANCES
	DROP CONSTRAINT FK__PERFORMAN__Caven__2D27B809

ALTER TABLE PERFORMANCES
	ADD CONSTRAINT FK_Cavent_id
		FOREIGN KEY (Cavent_id) 
			REFERENCES CAVENTS(id)
			ON DELETE CASCADE



ALTER TABLE APPEARANCES
	DROP CONSTRAINT FK__APPEARANC__Artis__300424B4

ALTER TABLE APPEARANCES
	ADD CONSTRAINT FK_Artist_id
		FOREIGN KEY (Artist_id)
			REFERENCES ARTISTS(id)
			ON DELETE CASCADE

ALTER TABLE APPEARANCES
	DROP CONSTRAINT FK__APPEARANC__Perfo__30F848ED

ALTER TABLE APPEARANCES
	ADD CONSTRAINT FK_Performance_id
		FOREIGN KEY (Performance_id)
			REFERENCES PERFORMANCES(id)
			ON DELETE CASCADE



ALTER TABLE TICKETS
	DROP CONSTRAINT FK__TICKETS__Cavent___3B75D760

ALTER TABLE TICKETS
	ADD CONSTRAINT FK_Cavent_id
		FOREIGN KEY (Cavent_id)
			REFERENCES CAVENTS(id)
			ON DELETE CASCADE

ALTER TABLE TICKETS
	DROP CONSTRAINT FK__TICKETS__Ticketh__3C69FB99

ALTER TABLE TICKETS
	ADD CONSTRAINT FK_Ticketholder_id
		FOREIGN KEY (Ticketholder_id)
			REFERENCES TICKETHOLDERS(id)
			ON DELETE CASCADE

ALTER TABLE TICKETS
	DROP CONSTRAINT FK__TICKETS__SeatNum__3E52440B

ALTER TABLE TICKETS
	ADD CONSTRAINT FK_SeatNumber_id
		FOREIGN KEY (SeatNumber_id)
			REFERENCES SEATNUMBERS(id)
			ON DELETE CASCADE

ALTER TABLE TICKETS
	DROP CONSTRAINT FK__TICKETS__SeatRow__3D5E1FD2

ALTER TABLE TICKETS
	ADD CONSTRAINT FK_SeatRow_id
		FOREIGN KEY (SeatRow_id)
			REFERENCES SEATROWS(id)
			ON DELETE CASCADE
