USE SINGLE_STAGE
GO


CREATE TABLE PERFORMANCES (
	id int PRIMARY KEY IDENTITY(1,1),
	Description varchar(100) NOT NULL,
	StartTime datetime NOT NULL,
	EndTime datetime NOT NULL,
	Cavent_id int NOT NULL,
	FOREIGN KEY (Cavent_id) REFERENCES CAVENTS(id)
	)

SELECT * FROM PERFORMANCES


CREATE TABLE APPEARANCES (
	id int PRIMARY KEY IDENTITY(1,1),
	RoyaltyAdvance decimal,
	RoyaltyAtEnd decimal,
	Artist_id int NOT NULL,
	FOREIGN KEY (Artist_id) REFERENCES ARTISTS(id),
	Performance_id int NOT NULL,
	FOREIGN KEY (Performance_id) REFERENCES PERFORMANCES(id)
	)

SELECT * FROM APPEARANCES


CREATE TABLE TICKETS (
	id int PRIMARY KEY IDENTITY(1,1),
	Cavent_id int NOT NULL,
	FOREIGN KEY (Cavent_id) REFERENCES CAVENTS(id),
	Ticketholder_id int NOT NULL,
	FOREIGN KEY (Ticketholder_id) REFERENCES TICKETHOLDERS(id),
	SeatRow_id int NOT NULL,
	FOREIGN KEY (SeatRow_id) REFERENCES SEATROWS(id),
	SeatNumber_id int NOT NULL,
	FOREIGN KEY (SeatNumber_id) REFERENCES SEATNUMBERS(id)
	)

SELECT * FROM TICKETS